name       : python-installer
version    : 0.5.1
release    : 1
source     :
    - https://github.com/pypa/installer/archive/refs/tags/0.5.1.tar.gz : 0a50c8d4d1bd8ff1e13fa24c479f04b4b1f1b7ea123c394a46aee85c6e94e16b
homepage   : https://github.com/pypa/installer
license    : MIT
component  : programming.python
summary    : A low-level library for installing from a Python wheel distribution
description: |
    This is a low-level library for installing a Python package from a wheel distribution. It provides basic functionality and abstractions for handling wheels and installing packages from wheels.
builddeps  :
    - python-build
    - python-flit-core
    - python-packaging
    - python-pytest     # check
build      : |
    python3 -m build --wheel --no-isolation
install    : |
    PYTHONPATH=src python3 -m installer --destdir=%installroot% dist/*.whl
check      : |
    PYTHONPATH=src pytest3
