name       : python-installer
version    : 0.7.0
release    : 6
source     :
    - https://github.com/pypa/installer/archive/refs/tags/0.7.0.tar.gz : e1589201863a6b6f570ce2f9994febe54a8d9196e0cc54fd331cd7ffd728fb86
homepage   : https://github.com/pypa/installer
license    : MIT
component  : programming.python
summary    : A low-level library for installing from a Python wheel distribution
description: |
    This is a low-level library for installing a Python package from a wheel distribution. It provides basic functionality and abstractions for handling wheels and installing packages from wheels.
builddeps  :
    - python-build
    - python-flit-core
    - python-packaging
    - python-pytest     # check
build      : |
    python3 -m build --wheel --no-isolation
install    : |
    PYTHONPATH=src python3 -m installer --destdir=%installroot% dist/*.whl
check      : |
    PYTHONPATH=src pytest3 -v
