name       : python-installer
version    : 1.6.0
release    : 4
source     :
    - https://github.com/pypa/installer/archive/refs/tags/0.6.0.tar.gz : b4df8cf5a649ff6f25cb885a7a93662f38229e05f1859db663f752a6203014f6
homepage   : https://github.com/pypa/installer
license    : MIT
component  : programming.python
summary    : A low-level library for installing from a Python wheel distribution
description: |
    This is a low-level library for installing a Python package from a wheel distribution. It provides basic functionality and abstractions for handling wheels and installing packages from wheels.
builddeps  :
    - python-build
    - python-flit-core
    - python-packaging
    - python-pytest     # check
build      : |
    python3 -m build --wheel --no-isolation
install    : |
    PYTHONPATH=src python3 -m installer --destdir=%installroot% dist/*.whl
check      : |
    PYTHONPATH=src pytest3
